name: Test Aplication with Github Acions and Prisma
on: push
jobs: 
    test:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: dev
                    POSTGRES_DB: dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env: 
            DATABASE_URL: postgres://postgres:dev@localhost:5432/dev
            DIRECT_URL: postgres://postgres:dev@localhost:5432/dev
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Use Node.js 18.5
              uses: actions/setup-node@v3
              with:
                node-version: 20.10
            - name: Install dependencies
              run:  npm install
            - name: Generate Prisma Client
              run: npx prisma db push
            - name: Run tests
              run: npm test